/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/asset_manager.h>
#include "audioFx/OpenSLEqualizer.h"
#include "logger/log.h"
#include <SLES/OpenSLES.h>
#include <SLES/OpenSLES_Android.h>
#include <stdio.h>
#include <assert.h>
#include <pthread.h>
#include <stdlib.h>
#include "android/asset_manager_jni.h"
/* Header for class com_example_openslplayer_OpenSLPlayer */

#ifndef AUDIOTRACKACTIVITY_H_
#define AUDIOTRACKACTIVITY_H_

#ifdef __cplusplus
extern "C" {
#endif
namespace android {
/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    createEngine
 * Signature: ()V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_createEngine
            (JNIEnv *, jclass);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    createAudioPlayer
 * Signature: (III)Z
 */
    jboolean Java_com_example_openslplayer_OpenSLPlayer_createAudioPlayer(JNIEnv *, jclass ,
                                                                          jint , jint , jint );

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    write
 * Signature: (Z)V
 */
    jint Java_com_example_openslplayer_OpenSLPlayer_write(JNIEnv *, jobject, jbyteArray, jint,
                                                          jint);


/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    setPlayingAudioPlayer
 * Signature: (Z)V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_setPlayingAudioPlayer
            (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    seekTo
 * Signature: (I)V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_seekTo(JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    setVolumeAudioPlayer
 * Signature: (I)V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_setVolumeAudioPlayer
            (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    setMutAudioPlayer
 * Signature: (Z)V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_setMutAudioPlayer
            (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    enableReverb
 * Signature: (Z)V
 */
    jboolean Java_com_example_openslplayer_OpenSLPlayer_enableReverb(JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    enableEqualizer
 * Signature: (Z)V
 */
    jboolean Java_com_example_openslplayer_OpenSLPlayer_enableEqualizer(JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openslplayer_OpenSLPlayer
 * Method:    shutdown
 * Signature: ()V
 */
    void Java_com_example_openslplayer_OpenSLPlayer_shutdown
            (JNIEnv *, jclass, jboolean);

    jboolean Java_com_example_openslplayer_OpenSLPlayer_readAsset(JNIEnv *, jclass, jobject);

};
#ifdef __cplusplus
}
#endif
#endif
